### ISSUE TITLE
Signing up with Azure AD does not set the users email

### ISSUE THREAD

**Issue by hk-meko** [nhost/hasura-auth#404] opened 2023-07-11 11:36 UTC
When using AzureAD for signup/ signin, the users email is not set in the database.
[This](https://github.com/nhost/hasura-auth/blob/87fee13f4e7b3ea33263323a27ecd3ac556f6eeb/src/routes/oauth/config.ts#L69C1-L88) part of the azuread config is the falsey part. The payload field containing the email is named "upn", in the config it's [email](https://github.com/nhost/hasura-auth/blob/87fee13f4e7b3ea33263323a27ecd3ac556f6eeb/src/routes/oauth/config.ts#L85)

```  
azuread: {
    grant: {
      oauth: 2,
      scope_delimiter: ' ',
      client_id: process.env.AUTH_PROVIDER_AZUREAD_CLIENT_ID,
      client_secret: process.env.AUTH_PROVIDER_AZUREAD_CLIENT_SECRET,
      authorize_url: `${azureBaseUrl}/[subdomain]/oauth2/authorize`,
      access_url: `${azureBaseUrl}/[subdomain]/oauth2/token`,
      profile_url: `${azureBaseUrl}/[subdomain]/openid/userinfo`,
      subdomain: process.env.AUTH_PROVIDER_AZUREAD_TENANT || 'common',
    },
    profile: ({ jwt }) => {
      const payload = jwt?.id_token?.payload;
      return {
        id: payload.oid,
        displayName: payload.name,
        email: payload.email,
      };
    },
  },
```

Here is a privatized OAuth response from AzureAD:

```
{
  "id_token": "...",
  "access_token": "...",
  "refresh_token": "...",
  "jwt": {
    "id_token": {
      "header": {
        "typ": "JWT",
        "alg": "none"
      },
      "payload": {
        "aud": "...",
        "iss": "https://sts.windows.net/.../",
        "iat": 1689073876,
        "nbf": 1689073876,
        "exp": 1689077776,
        "amr": [
          "pwd",
          "mfa"
        ],
        "family_name": "Doe",
        "given_name": "John",
        "ipaddr": "12.345.78.912",
        "name": "John Doe",
        "oid": "...",
        "onprem_sid": "...",
        "rh": "...",
        "sub": "...",
        "tid": "...",
        "unique_name": "email@email.com",
        "upn": "email@email.com",
        "ver": "1.0"
      },
      "signature": ""
    }
  },
  "profile": {
    "error": {}
  }
}
```

I hope this can be fixed quickly, with the provided information.

**Comment by dbarrosop** [comment] 2023-07-11 11:46
Given you have already identified the root cause and are a bit in a hurry here, would you mind opening a PR fixing it? Thanks!

**Comment by dbarrosop** [comment] 2023-07-11 14:41
Closing as per the following comment: https://github.com/nhost/hasura-auth/pull/405#issuecomment-1630951568

**Closed** 2023-07-12 05:56 UTC
