### ISSUE TITLE
Allow to switch to camelCase by config

### ISSUE THREAD

**Issue by tdelabro** [nhost/hasura-auth#316] opened 2022-12-28 09:14 UTC
Currently hasura-auth expects arguments as snake_case.
For our project, we would prefer camelCase to maintain coherence.
We did a fork with some changes looking something like this: https://github.com/nhost/hasura-auth/pull/304/files. 
In the meantime, you did a big refacto of the codebase and we cannot rebase anymore :,(

Are you open to a PR introducing a way to configure if the project should use camelCase or snake_case?
If yes we will propose something :)

**Comment by plmercereau** [comment] 2022-12-28 14:59
Hi Timothée,
This is a duplicate of https://github.com/nhost/hasura-auth/issues/289, I will reply in the other thread

**Closed by plmercereau** 2022-12-28 14:59 UTC
