### ISSUE TITLE
Social Login with LinkedIn throws 500 when user cancel autorization

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#171] opened 2022-05-30 01:05 UTC
If the user tries to sign in through Linkedin and then, when arriving at the screen: 
![image](https://user-images.githubusercontent.com/8176422/170899877-2d9ccb88-a06f-47c6-a909-8c5192249799.png)
and if you click cancel, you'll be redirected to this page:
https://fkxqztcepombfuibkyom.nhost.run/v1/auth/signin/provider/linkedin/callback?error=user_cancelled_authorize&error_description=The+user+cancelled+the+authorization&state=a9156bbe-0849-4747-97a1-3bafa6214215
And it will throw a 500 error.

**Comment by elitan** [comment] 2022-06-07 06:56
duplicate of: https://github.com/nhost/hasura-auth/issues/125

**Closed by elitan** 2022-06-07 06:56 UTC
Labels: bug
